#[line_break]
#disabled=true

#custom format from dt
#format = """
#[---------------->](bold green)
#[|]
#(bold green)$directory$rust$package
#[-->](bold green)
#"""

[python]
symbol = "î˜†  "
pyenv_version_name = true


[git_branch]
symbol = "îœ¥ "
truncation_length = 10
truncation_symbol = ""
#ignore_branches = ["master", "main"]


[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[îŠ› PICKING](bold red)"


[git_status]
conflicted = "ğŸ³"
ahead = "ğŸ "
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ïƒ§ "
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
