#[line_break]
#disabled=true

#custom format from dt
format = """
[---------------->](bold green)
[|](bold green)$directory$rust$package
[-->](bold green)"""

# ~/.config/starship.toml

[git_branch]
symbol = "îœ¥"
truncation_length = 4
truncation_symbol = ""
ignore_branches = ["master", "main"]


# git stat on rebase etc....

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"


[git_status]
conflicted = "ğŸ³"
ahead = "ğŸ "
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
